version: "3.9"

services:
  redis-node1:
    network_mode: "host"
    image: redis:latest
    container_name: redis-node1
    ports: 
      - 6300:6300

    volumes:
      - ./redis1.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  redis-node2:
    network_mode: "host"
    image: redis:latest
    container_name: redis-node2
    ports: 
      - 6301:6301
    volumes:
      - ./redis2.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf

  redis-node3:
    network_mode: "host"
    image: redis:latest
    container_name: redis-node3
    ports: 
      - 6302:6302
    volumes:
      - ./redis3.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
